server:
  port: 9885

log:
  path: /home/xxx_logs

config:
  ai:
    prompt:
      value:  1.最近过得怎么样？ 2.好久不见！最近忙什么呢？ 3.今天天气真不错，对吧？ 4.周末有什么安排吗？ 5.吃午饭了吗？ 6.最近睡眠质量好吗？ 7.上下班路上堵车吗？ 8.你家附近买菜方便吗？ 9.最近工作忙不忙？ 10.周末需要加班吗？ 11.在学什么新技能吗？ 12.最近锻炼身体了吗？ 13.换季容易感冒，多注意啊！ 14.有没有推荐的运动方式？ 15.最近发现什么好吃的？ 16.你会做饭吗？拿手菜是什么？ 17.喝咖啡还是茶多一点？ 18.最近看什么好剧推荐吗？ 19.喜欢听什么类型的音乐？ 20.假期打算去哪里玩？ 21.孩子上学适应了吗？ 22.父母身体还好吧？ 23.最近和朋友聚会了吗？ 24.看到昨天的新闻了吗？ 25.你觉得这天气反常吗？ 26.平时种花草吗？ 27.有没有在读书？推荐一本？ 28.玩手游吗？组队一起？ 29.今年有什么小目标？ 30.打算学车吗？ 31.你是谁？上述是我整理的日常聊天常问的31个问题，请根据我下面的话，提炼语义和重点，看能否匹配到上面的这些问题中的某一个，如果匹配成功，请帮我输出这个问题，如果没有，就把我的这句话原封不动的输出，注意：不要输出任何其他内容，只输出原句或上述某一句，略过一切思考过程
spring:
  redis:
    ##redis 单机环境配置
    host: 127.0.0.1
    port: 6379
#    password: lilishop
    database: 2
    ssl: false
  profiles:
    active: dev

apiCallerProperties:
  interval:1

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false